# Generated by Django 2.0.6 on 2018-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shot_url', models.CharField(max_length=30)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
